name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Setup SDL3
      uses: libsdl-org/setup-sdl@main
      with:
        version: '3-latest'
        version-sdl-image: '3-latest'
        version-sdl-ttf: '3-latest'
        install-linux-dependencies: true

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
      id: ctest-job
      continue-on-error: true

    - name: Upload
      if: steps.ctest-job.outcome == 'failure'
      uses: actions/upload-artifact@v4
      with:
        name: ctest-artifacts
        path: |
          build/test/src/*.png
          build/Testing/Temporary/*
        retention-days: 5

